/* atr_tab.h */

#ifndef __ATR_TAB_H
#define __ATR_TAB_H

#include "attrib.h"

/* attribute list */
ATTR attr[] =
{
  {(char *) "AAHEAR", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ACLONE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ACONNECT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ADEATH", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ADESCRIBE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ADESTROY", AF_WIZARD | AF_PRIVATE | AF_NOCOPY, NULL, 0, NULL},
  {(char *) "ADISCONNECT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ADROP", AF_NOPROG, NULL, 0, NULL},
  {(char *) "AEFAIL", AF_NOPROG, NULL, 0, NULL},
  {(char *) "AENTER", AF_NOPROG, NULL, 0, NULL},
  {(char *) "AFAILURE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "AHEAR", AF_NOPROG, NULL, 0, NULL},
  {(char *) "AIDESCRIBE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ALEAVE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ALFAIL", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ALIAS", AF_VISUAL | AF_NOPROG, NULL, 0, NULL},
#ifdef USE_MAILER
  {(char *) "AMAIL", AF_WIZARD, NULL, 0, NULL},
#endif
  {(char *) "AMHEAR", AF_NOPROG, NULL, 0, NULL},
  {(char *) "AMOVE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "APAYMENT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ASUCCESS", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ATPORT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "AUFAIL", AF_NOPROG, NULL, 0, NULL},
  {(char *) "AUSE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "AWAY", AF_NOPROG, NULL, 0, NULL},
  {(char *) "CHARGES", AF_NOPROG, NULL, 0, NULL},
  {(char *) "COMMENT", AF_NOPROG | AF_MDARK | AF_WIZARD, NULL, 0, NULL},
  {(char *) "CONFORMAT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "COST", AF_NOPROG, NULL, 0, NULL},
  {(char *) "DEATH", AF_NOPROG, NULL, 0, NULL},
  {(char *) "DESCRIBE", AF_VISUAL | AF_NOPROG, NULL, 0, NULL},
  {(char *) "DROP", AF_NOPROG, NULL, 0, NULL},
  {(char *) "EALIAS", AF_NOPROG, NULL, 0, NULL},
  {(char *) "EFAIL", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ENTER", AF_NOPROG, NULL, 0, NULL},
  {(char *) "EXITFORMAT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "FAILURE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "FILTER", AF_NOPROG, NULL, 0, NULL},
#ifdef FOLLOW
  {(char *) "FOLLOWING", AF_NOPROG | AF_PRIVATE |
   AF_WIZARD | AF_NOCOPY, NULL, 0, NULL},
  {(char *) "FOLLOWERS", AF_NOPROG | AF_PRIVATE |
   AF_WIZARD | AF_NOCOPY, NULL, 0, NULL},
#endif
  {(char *) "HAVEN", AF_NOPROG, NULL, 0, NULL},
  {(char *) "IDESCRIBE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "IDLE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "INFILTER", AF_NOPROG, NULL, 0, NULL},
  {(char *) "INPREFIX", AF_NOPROG, NULL, 0, NULL},
  {(char *) "LALIAS", AF_NOPROG, NULL, 0, NULL},
  {(char *) "LAST", AF_VISUAL | AF_WIZARD | AF_LOCKED, NULL, 0, NULL},
  {(char *) "LASTIP", AF_LOCKED, NULL, 0, NULL},
  {(char *) "LASTFAILED", AF_WIZARD | AF_LOCKED, NULL, 0, NULL},
  {(char *) "LASTPAGED", AF_WIZARD | AF_LOCKED, NULL, 0, NULL},
  {(char *) "LASTSITE", AF_LOCKED, NULL, 0, NULL},
  {(char *) "LEAVE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "LFAIL", AF_NOPROG, NULL, 0, NULL},
  {(char *) "LISTEN", AF_NOPROG, NULL, 0, NULL},
#ifdef USE_MAILER
  {(char *) "MAILCURF", AF_WIZARD | AF_NOPROG | AF_LOCKED, NULL, 0, NULL},
  {(char *) "MAILFILTERS", AF_WIZARD | AF_NOPROG | AF_LOCKED, NULL, 0, NULL},
  {(char *) "MAILFOLDERS", AF_WIZARD | AF_NOPROG | AF_LOCKED, NULL, 0, NULL},
  {(char *) "MAILSIGNATURE", AF_NOPROG, NULL, 0, NULL},
#endif
  {(char *) "MOVE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ODEATH", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ODESCRIBE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "ODROP", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OEFAIL", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OENTER", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OFAILURE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OIDESCRIBE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OLEAVE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OLFAIL", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OMOVE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OPAYMENT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OXMOVE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OSUCCESS", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OTPORT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OUFAIL", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OUSE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OXENTER", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OXLEAVE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "OXTPORT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "PAYMENT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "PREFIX", AF_NOPROG, NULL, 0, NULL},
  {(char *) "PURSE", AF_WIZARD | AF_LOCKED |
   AF_PRIVATE | AF_NOCOPY, NULL, 0, NULL},
  {(char *) "QUEUE", AF_MDARK | AF_WIZARD, NULL, 0, NULL},
  {(char *) "REGISTERED_EMAIL", AF_WIZARD | AF_LOCKED | AF_PRIVATE | AF_NOCOPY, NULL, 0, NULL},
  {(char *) "RQUOTA", AF_MDARK | AF_LOCKED, NULL, 0, NULL},
  {(char *) "RUNOUT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "SEMAPHORE", AF_LOCKED | AF_PRIVATE, NULL, 0, NULL},
  {(char *) "SEX", AF_VISUAL | AF_NOPROG, NULL, 0, NULL},
  {(char *) "STARTUP", AF_NOPROG, NULL, 0, NULL},
  {(char *) "SUCCESS", AF_NOPROG, NULL, 0, NULL},
  {(char *) "TFPREFIX", AF_NOPROG | AF_NOCOPY | AF_PRIVATE, NULL, 0, NULL},
  {(char *) "TPORT", AF_NOPROG, NULL, 0, NULL},
  {(char *) "UFAIL", AF_NOPROG, NULL, 0, NULL},
  {(char *) "USE", AF_NOPROG, NULL, 0, NULL},
  {(char *) "VA", 0, NULL, 0, NULL},
  {(char *) "VB", 0, NULL, 0, NULL},
  {(char *) "VC", 0, NULL, 0, NULL},
  {(char *) "VD", 0, NULL, 0, NULL},
  {(char *) "VE", 0, NULL, 0, NULL},
  {(char *) "VF", 0, NULL, 0, NULL},
  {(char *) "VG", 0, NULL, 0, NULL},
  {(char *) "VH", 0, NULL, 0, NULL},
  {(char *) "VI", 0, NULL, 0, NULL},
  {(char *) "VJ", 0, NULL, 0, NULL},
  {(char *) "VK", 0, NULL, 0, NULL},
  {(char *) "VL", 0, NULL, 0, NULL},
  {(char *) "VM", 0, NULL, 0, NULL},
  {(char *) "VN", 0, NULL, 0, NULL},
  {(char *) "VO", 0, NULL, 0, NULL},
  {(char *) "VP", 0, NULL, 0, NULL},
  {(char *) "VQ", 0, NULL, 0, NULL},
  {(char *) "VR", 0, NULL, 0, NULL},
  {(char *) "VRML_URL", AF_NOPROG, NULL, 0, NULL},
  {(char *) "VS", 0, NULL, 0, NULL},
  {(char *) "VT", 0, NULL, 0, NULL},
  {(char *) "VU", 0, NULL, 0, NULL},
  {(char *) "VV", 0, NULL, 0, NULL},
  {(char *) "VW", 0, NULL, 0, NULL},
  {(char *) "VX", 0, NULL, 0, NULL},
  {(char *) "VY", 0, NULL, 0, NULL},
  {(char *) "VZ", 0, NULL, 0, NULL},
  {(char *) "WA", 0, NULL, 0, NULL},
  {(char *) "WB", 0, NULL, 0, NULL},
  {(char *) "WC", 0, NULL, 0, NULL},
  {(char *) "WD", 0, NULL, 0, NULL},
  {(char *) "WE", 0, NULL, 0, NULL},
  {(char *) "WF", 0, NULL, 0, NULL},
  {(char *) "WG", 0, NULL, 0, NULL},
  {(char *) "WH", 0, NULL, 0, NULL},
  {(char *) "WI", 0, NULL, 0, NULL},
  {(char *) "WJ", 0, NULL, 0, NULL},
  {(char *) "WK", 0, NULL, 0, NULL},
  {(char *) "WL", 0, NULL, 0, NULL},
  {(char *) "WM", 0, NULL, 0, NULL},
  {(char *) "WN", 0, NULL, 0, NULL},
  {(char *) "WO", 0, NULL, 0, NULL},
  {(char *) "WP", 0, NULL, 0, NULL},
  {(char *) "WQ", 0, NULL, 0, NULL},
  {(char *) "WR", 0, NULL, 0, NULL},
  {(char *) "WS", 0, NULL, 0, NULL},
  {(char *) "WT", 0, NULL, 0, NULL},
  {(char *) "WU", 0, NULL, 0, NULL},
  {(char *) "WV", 0, NULL, 0, NULL},
  {(char *) "WW", 0, NULL, 0, NULL},
  {(char *) "WX", 0, NULL, 0, NULL},
  {(char *) "WY", 0, NULL, 0, NULL},
  {(char *) "WZ", 0, NULL, 0, NULL},
  {(char *) "XA", 0, NULL, 0, NULL},
  {(char *) "XB", 0, NULL, 0, NULL},
  {(char *) "XC", 0, NULL, 0, NULL},
  {(char *) "XD", 0, NULL, 0, NULL},
  {(char *) "XE", 0, NULL, 0, NULL},
  {(char *) "XF", 0, NULL, 0, NULL},
  {(char *) "XG", 0, NULL, 0, NULL},
  {(char *) "XH", 0, NULL, 0, NULL},
  {(char *) "XI", 0, NULL, 0, NULL},
  {(char *) "XJ", 0, NULL, 0, NULL},
  {(char *) "XK", 0, NULL, 0, NULL},
  {(char *) "XL", 0, NULL, 0, NULL},
  {(char *) "XM", 0, NULL, 0, NULL},
  {(char *) "XN", 0, NULL, 0, NULL},
  {(char *) "XO", 0, NULL, 0, NULL},
  {(char *) "XP", 0, NULL, 0, NULL},
  {(char *) "XQ", 0, NULL, 0, NULL},
  {(char *) "XR", 0, NULL, 0, NULL},
  {(char *) "XS", 0, NULL, 0, NULL},
  {(char *) "XT", 0, NULL, 0, NULL},
  {(char *) "XU", 0, NULL, 0, NULL},
  {(char *) "XV", 0, NULL, 0, NULL},
  {(char *) "XW", 0, NULL, 0, NULL},
  {(char *) "XX", 0, NULL, 0, NULL},
  {(char *) "XY", 0, NULL, 0, NULL},
  {(char *) "XZ", 0, NULL, 0, NULL},
  {(char *) "XYXXY", AF_INTERNAL | AF_NOPROG | AF_LOCKED | AF_WIZARD,
   NULL, 0, NULL},
#ifdef TREKMUSH
  {(char *) "CONSOLE", AF_WIZARD | AF_MDARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "CMDS", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "EMAIL", AF_WIZARD | AF_MDARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "EXPERIENCE", AF_WIZARD | AF_MDARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "LANGUAGES", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "MAGLST", AF_WIZARD | AF_MDARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "MAGCURRENT", AF_WIZARD | AF_MDARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "MONEY", AF_WIZARD | AF_ODARK | AF_NOPROG | AF_NOCOPY, NULL, 0, NULL},
  {(char *) "MASTERORG", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "ORGANIZATION", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "PID", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "POSITION", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "RACE", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "RANK", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "ROOMTYPE", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "SKILLS", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "SPEAKING", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
  {(char *) "TRUERACE", AF_WIZARD | AF_ODARK | AF_NOPROG, NULL, 0, NULL},
#endif /* TREKMUSH */
  {NULL, 0, NULL, 0, NULL}
};

#endif				/* __ATR_TAB_H */
