 {(char *)"speak",		NULL,		0,
 	0,		CS_ONE_ARG,			do_speak},
 {(char *)"unpack",		NULL,		0,
 	0,		CS_ONE_ARG,			do_unpack},

 {(char *)"press",		NULL,		0,
 	0,		CS_ONE_ARG,			do_press},

 {(char *)"epay",		NULL,		0,
 	0,		CS_ONE_ARG,			do_epay},
 {(char *)"egive",		NULL,		0,
 	0,		CS_ONE_ARG,			do_egive},


 {(char *)"cpage",		NULL,		0,
 	0,		CS_ONE_ARG,			do_cpage},
 {(char *)"ctune",		NULL,		0,
 	0,		CS_ONE_ARG,			do_cset},
 {(char *)"ctran",		NULL,		0,
 	0,		CS_ONE_ARG,			do_ctran},
 {(char *)"turn",		NULL,		0,
 	0,		CS_ONE_ARG,			do_turn},

 {(char *)"listskills",		NULL,		0,
 	0,		CS_NO_ARGS,			do_testskill},
 {(char *)"release",		NULL,		0,
 	0,		CS_NO_ARGS,			do_release},
 {(char *)"remove",		NULL,		0,
 	0,		CS_NO_ARGS,			do_unwear},
 {(char *)"unwield",		NULL,		0,
 	0,		CS_NO_ARGS,			do_unwield},

 {(char *)"money",		NULL,		0,
 	0,		CS_NO_ARGS,			do_see_money},
 {(char *)"commods",		NULL,		0,
 	0,		CS_NO_ARGS,			see_commods},
 {(char *)"econlist",		NULL,		0,
 	0,		CS_NO_ARGS,			do_econlist},

 {(char *)"qstats",		NULL,		0,
 	0,		CS_ONE_ARG,			see_qskills},
 {(char *)"stats",		NULL,		0,
 	0,		CS_ONE_ARG,			see_skills},

 {(char *)"attack",		NULL,		0,
 	0,		CS_ONE_ARG,			do_attack},

 {(char *)"affect",		NULL,		0,
 	0,		CS_ONE_ARG,			do_affect},
 {(char *)"grab",		NULL,		0,
 	0,		CS_ONE_ARG,			do_grab},
 {(char *)"eat",		NULL,		0,
 	0,		CS_ONE_ARG,			do_eat},
 {(char *)"drink",		NULL,		0,
 	0,		CS_ONE_ARG,			do_drink},
 {(char *)"listaddplay",		NULL,		0,
 	0,		CS_ONE_ARG,			do_icstuff},
 {(char *)"listrmplay",		NULL,		0,
 	0,		CS_ONE_ARG,			do_oocstuff},
 {(char *)"wear",		NULL,		0,
 	0,		CS_ONE_ARG,			do_wear},
 {(char *)"wield",		NULL,		0,
 	0,		CS_ONE_ARG,			do_wield},
 {(char *)"rest",		NULL,		0,
 	0,		CS_NO_ARGS,			do_rest},
 {(char *)"cease",		NULL,		0,
 	0,		CS_NO_ARGS,			do_stop},
 {(char *)"reload",		NULL,		0,
 	0,		CS_NO_ARGS,			do_reload},

